name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push a new tag
    if: "contains(github.event.head_commit.message, 'chore(release):')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from datapackage.json
        id: package_version
        run: |
          echo "version=$(jq -r .version datapackage.json)" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "v${{ steps.package_version.outputs.version }}" -m "Release v${{ steps.package_version.outputs.version }}"
          git push origin "v${{ steps.package_version.outputs.version }}"

      - name: Create Release Assets
        run: |
          zip -r unique-names-data.zip data/ datapackage.json README.md LICENSE
          tar -czvf unique-names-data.tar.gz data/ datapackage.json README.md LICENSE

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.package_version.outputs.version }}"
          name: "Release v${{ steps.package_version.outputs.version }}"
          body: |
            Release of version ${{ steps.package_version.outputs.version }}.
            See the [CHANGELOG.md](CHANGELOG.md) for details.
          files: |
            unique-names-data.zip
            unique-names-data.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
